### PR TITLE
Sort by EXIF 'taken' date

### PR DESCRIPTION
**Pull request by denim2x**
Fixes: #51

Licence: AGPL

### Description
Attempts to implement new feature: *sort by EXIF 'taken' date*; new button added to the interface -
 switches `sortType` to `date-taken`, causes the files to be sorted by their `exif.taken_date` properties.

### Features
- new button for sorting by EXIF 'taken' date
- improved JS code for supporting new `sortTypes`
- `FilesService.php` improvements
  - `getNodeData()` return value has new `exif` attribute;
  - new method `getEXIF()` for retrieving specific EXIF data
    * `taken_date` attribute (UNIX timestamp) maps to `DateTimeOriginal` EXIF field; defaults to `0`.

### Screenshots or screencasts
[ screencast](https://www.screencast.com/t/YJ1vOm9VWAiF)

### Caveats
―

### Test plan
Update *Gallery* app, launch Nextcloud, navigate to *Gallery*, open any album, click on *Sort by EXIF taken date* button (next to the *Sort by modified date* button); the ordering should change depending on each photo's `exif.taken_date` property.
 
### Tested on
- [x] Windows/Opera
- [ ] Windows/Firefox
- [ ] Android 6.1/Chrome

### TODO
- [ ] Optimize backend code through caching (*Redis*, *MySQL*)

### Check list

- [x] Code is properly documented
- [x] Code is properly formatted
- [x] Commits have been squashed
- [ ] Tests (unit, integration, api and/or acceptance) are included
- [ ] Documentation (manuals or wiki) has been updated or is not required

### Reviewers
@oparoz, @jancborchardt

### CODE REVIEW

**Comment by denim2x** [comment]
@oparoz What can I do about the failed *SignInAsUserCept* test?

**Comment by jancborchardt** [comment]
A code review please :) @rullzer @MorrisJobke @lcalaresu @irgendwie @skjnldsv

**Comment by oparoz** [comment]
> @oparoz What can I do about the failed SignInAsUserCept test?

You can open another PR if you want, the CSS for the menu item has changed, so the acceptance test fails.

**Comment by patman15** [comment]
Since my name is mentioned under "Reviewers", I'm too far away from the project to provide reasonable feedback. I can test if you want. Let me know if "easy" tasks are required I would support that.

**Comment by oparoz** [comment]
Regarding this PR, my biggest issue is that the information is never saved, which will lead to a performance hit, which should be measured.

I think a better option is still to have some form of meta data extraction being performed at upload time and it should be a core functionality of the server since it isn't only useful for images, but lots of other file types.

**Comment by jancborchardt** [comment]
Then we should continue in the core issue at https://github.com/nextcloud/server/issues/5106 ?

**Comment by oparoz** [comment]
Correct. And once EXIF data is available via an API, then we can re-activate this PR and create lots of fun others :)

**Comment by jancborchardt** [comment]
Closing then as we should work on this in core as commented. @denim2x let’s continue in the core issue at nextcloud/server#5106 

Please also note that we will likely focus our efforts on the [upcoming grid view of Files](https://github.com/nextcloud/server/pull/11573) rather than Gallery.

**Pull request closed without merging**
