### PR TITLE
Add a favicon

### PR DESCRIPTION
**Pull request by roipoussiere**
Fixes: #207

Licence: MIT or AGPL

### Description

Add a favicon for the Gallery app.

### Test plan

Open the gallery app and check for the new favicon on your browser, dedicated to this app.
 
### Tested on

- [x] Firefox

### Check list

- [x] Code is properly documented
- [x] Code is properly formatted
- [x] Commits have been squashed
- [x] Tests (unit, integration, api and/or acceptance) are included
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by oparoz** [comment]
@jancborchardt Could you review if this is OK? I think svg and png need to be stripped, but the documentation seems to be missing/too well hidden

**Comment by roipoussiere** [comment]
svg and psg are based on Calendar icon. I have not added documentation, is it needed for this?

**Comment by oparoz** [comment]
No documentation is needed :)

But we use apps to strip unnecessary metadata from graphics files. There used to be some documentation somewhere about which apps and how to use them, but I can't find it at the moment.

**Comment by jaller94** [comment]
Inkscape offers the option to Save As... "Plain SVG" which removes the common Inkscape related tags and transforms text to paths.
While I agree that SVGs should be shipped without those metadata editing the icon will be much easier if a copy of the Inkscape SVG is kept (in the repository to keep it public).

**Comment by oparoz** [comment]
> While I agree that SVGs should be shipped without those metadata editing the icon will be much easier if a copy of the Inkscape SVG is kept (in the repository to keep it public).

Sure, we could add `-inkscape` to the original file.

**Comment by jancborchardt** [comment]
Since the Gallery app is so core and basically almost belongs to the Files app, I would prefer we use the standard Nextcloud logo as favicon here, as we also do for the Files app.

**Comment by jancborchardt** [comment]
Since the Gallery app is so core and basically almost belongs to the Files app, I would prefer we use the standard Nextcloud logo as favicon here, as we also do for the Files app. cc @nextcloud/designers

**Comment by jaller94** [comment]
I would prefer a different icon for the reason that the favicon will be used in the browser bookmarks. It's especially useful when you remove the text to save space in your bookmark toolbar.

**Comment by jancborchardt** [comment]
Ok, then can you please compress the SVG using scour, preferably with the code line in core/img/image-optimization.sh? :)

**Comment by enoch85** [comment]
I also prefer a different icon. Look at calendar and contacts for example.

**Comment by juliushaertl** [comment]
Adding a favicon will also make it consistent to setups where the favicon will be generated by the theming app. So :+1: for that.

**Comment by roipoussiere** [comment]
> Ok, then can you please compress the SVG using scour, preferably with the code line in core/img/image-optimization.sh? :)

Ok.

> I also prefer a different icon. Look at calendar and contacts for example.

The icon I propose is similar to the calendar and contacts icons for me, what do you except?

**Comment by jancborchardt** [comment]
@roipoussiere I think @enoch85 was agreeing with @jaller94 that your change is good. :)

So you simply need to compress it and we can review + merge. The PNG ideally you can compress with optipng or [Trimage](https://trimage.org/). :)

**Comment by jancborchardt** [comment]
This is already fixed now through the automatic generation of favicons. :slightly_smiling_face:
@roipoussiere sorry that your change is not needed anymore, but looking forward to further contributions! :tada: 

image

**Pull request closed without merging**
