### PR TITLE
use Federated Cloud ID wording

### PR DESCRIPTION
**Pull request by jancborchardt**
Like for the server as well: https://github.com/nextcloud/server/pull/2132

Please review @oparoz @karlitschek @schiessle

### CODE REVIEW

**Comment by karlitschek** [comment]
:+1:

**Comment by oparoz** [comment]
:+1: 

Merge is pending resolution of https://github.com/nextcloud/server/issues/2135

**Comment by nickvergessen** [comment]
Backport please

**Comment by jancborchardt** [comment]
Backport at https://github.com/nextcloud/gallery/pull/176

**Pull request merged**
