### PR TITLE
Fixes relative heights for containers

### LINKED ISSUE #364: 13.0.0 RC1 Gallery while logged contains fewer photos than the same gallery using the share link
(system info in https://github.com/nextcloud/server/issues/7841)

When I am logged into Nextcloud, and view a directory of images using Files, I see everything that is there.
If I switch to grid view/Gallery, I see far fewer photos, like it is paginating but not giving me the option to go to the next page.

The same folder is shared using a share link, there all photos are always visible.

I don't remember having this problem in 12

### PR DESCRIPTION
**Pull request by pixelipo**
This should fix #364 

I still wasn't able to reproduce it (that's why I didn't notice it in my original PR), but I have a hunch that this is what was causing the issue. Please check if it really fixes it.

### CODE REVIEW

**Comment by pixelipo** [comment]
Done, @danxuliu

**Comment by MorrisJobke** [comment]
@pixelipo Could you backport this to the stable13 branch? Thanks

**Comment by MorrisJobke** [comment]
stable13 d654209

**Comment by pixelipo** [comment]
Thanks, @MorrisJobke - I was just about to backport when I noticed you already did it :)

**Pull request merged**
