### PR TITLE
Only load scripts on the files and sharing pages

### PR DESCRIPTION
**Pull request by nickvergessen**
Ref https://github.com/nextcloud/server/pull/2448
Licence: AGPL

@oparoz

### CODE REVIEW

**Comment by oparoz** [comment]
Hold on I thought we had this new way of asking Files to load scripts (loadAdditionalScript or something). Wouldn't that be a better solution?

**Comment by nickvergessen** [comment]
Yes, if that is enough use that:
https://github.com/nextcloud/files_texteditor/blob/master/appinfo/app.php#L5

**Comment by nickvergessen** [comment]
Updated, for better diff see https://github.com/nextcloud/gallery/pull/181/files?w=1

**Comment by oparoz** [comment]
Thanks for the update, the only thing missing is the same thing for public pages. @rullzer had added it to 10 I think.

**Comment by nickvergessen** [comment]
I thought that was the same, but It only has a similar name. Fixed.

**Comment by rullzer** [comment]
Ah yes we can do that now that oC support is gone. :+1:

**Pull request merged**
