### PR TITLE
[stable12] Ignore unavailable storage instead of breaking for all

### PR DESCRIPTION
**Pull request by MorrisJobke**
* backport of #327

### CODE REVIEW

**Comment by oparoz** [comment]
This cannot be merged before Travis is fixed to track stable12
https://travis-ci.org/nextcloud/gallery/jobs/308956901#L468

**Comment by MorrisJobke** [comment]
> This cannot be merged before Travis is fixed to track stable12

Let's see if my change fixes this.

**Comment by MorrisJobke** [comment]
There are 3 failures ... do you think they are related?

**Comment by oparoz** [comment]
> There are 3 failures ... do you think they are related?

No, it's all good.
The 2 acceptance tests don't work on stable12 unless the fix is backported
The integration test is a regression, no idea yet from which PR

**Pull request merged**
