### PR TITLE
fix share link button label

### PR DESCRIPTION
**Pull request by jancborchardt**
Please review @oparoz @LukasReschke @MorrisJobke

### CODE REVIEW

**Comment by jancborchardt** [comment]
Backports at https://github.com/nextcloud/gallery/pull/7 and https://github.com/nextcloud/gallery/pull/8

**Comment by oparoz** [comment]
Just a not to say that I saw the PR. I'm just not sure whether we should use Nextcloud or a more neutral name.

**Comment by jancborchardt** [comment]
Yeah, we thought about this already in ownCloud times. The problem is that it needs to be very descriptive so people understand. If it’s too generic then it seems like you can also edit it to completely different systems.

For now let’s please fix this issue. Having a generic name is an entirely different discussion.

Please review this and #7 and #8 cc @oparoz @nextcloud/designers @hannesfritz ;)

**Comment by oparoz** [comment]
A tooltip listing some options would be a good first step.

**Comment by jancborchardt** [comment]
As said, different discussion. We have to fix this issue asap because otherwise it’s a wrong name in our release.

cc @karlitschek @jospoortvliet

**Pull request merged**
