### PR TITLE
Spelling: Nextcloud

### PR DESCRIPTION
**Pull request by comradekingu**
Licence: MIT or AGPL

### CODE REVIEW

**Comment by rakekniven** [comment]
Hey @comradekingu Build failed due to missing git sign. Same for for me many times.
Are you using GitHub WebUI or git command line or other client supporting signing?

**Comment by comradekingu** [comment]
@rakekniven Depends what it is. For these easy things I just use the web UI.
At my cabin, and don't have the care or equipment to set up a new key.

**Comment by MorrisJobke** [comment]
stable12 f36635b

**Comment by MorrisJobke** [comment]
stable11 c709b3c

**Pull request merged**
