### PR TITLE
Force close all tooltips when closing sharing menu

### PR DESCRIPTION
**Pull request by skjnldsv**
Gallery app Share option ballon tooltip (2)
Gallery app Share option ballon tooltip not dissapearing (2)

### CODE REVIEW

**Comment by pielonet** [comment]
Hi,
I tested the changes on my own Nextcloud 17.0.0.9 but it does not seem to fix the bug : the tooltip remains !
Can you check ?
Best regards,
Thierry

**Comment by skjnldsv** [comment]
@pielonet after closing the sharing "sidebar"?
Make sure your cache is cleared please

1. [clear your browser's cache](https://www.refreshyourcache.com/)
2. [run](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/occ_command.html#run-occ-as-your-http-user) an [`occ maintenance:repair`](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/occ_command.html#maintenance-commands-label) on your server

Thanks :wink:

**Comment by pielonet** [comment]
Hi,
I did both :
- Clear browser cache
- occ maintenance:repair
plus :
- Checked that the javascript changes were in the downloaded files
The tooltip still remains when closing the side pane or clicking on files' home.

**Comment by skjnldsv** [comment]
> * The tooltip still remains when closing the side pane or clicking on files' home.

In the gallery still? Can you post some screenshots?

**Comment by pielonet** [comment]
Here is the screenshot

Capture d’écran_2019-10-09_15-21-41

**Comment by skjnldsv** [comment]
But this is not on gallery? I fail to understand the relevance here :thinking:

**Comment by pielonet** [comment]
If not gallery, which app is the file App then ?

**Comment by pielonet** [comment]
I guess this issue ALSO concerns the file App !

**Comment by pielonet** [comment]
@skjnldsv  Can you then please create a pr to solve the issue with tooltips in the share tab in the Files App ?

**Comment by skjnldsv** [comment]
> @skjnldsv Can you then please create a pr to solve the issue with tooltips in the share tab in the Files App ?

Sure thing! :)

I'll have to check if it's the same issue on files!

**Pull request merged**
