### PR TITLE
Move away from legacy OC_L10N

### PR DESCRIPTION
**Pull request by MorrisJobke**
See https://github.com/nextcloud/server/pull/1948

cc @oparoz

### CODE REVIEW

**Comment by rullzer** [comment]
LGTM.
Travis is complaining. Seems they upgraded phpunit

**Comment by oparoz** [comment]
Hmmm... "You" have probably made changes to your test class again in server.

Since there is no dev ML at NC, these sort of changes should be announced in the forums.

**Comment by MorrisJobke** [comment]
> Hmmm... "You" have probably made changes to your test class again in server.
> 
> Since there is no dev ML at NC, these sort of changes should be announced in the forums.

Looking at @rullzer and @nickvergessen

**Comment by nickvergessen** [comment]
No, we fixed the test class to stay compatible

**Comment by oparoz** [comment]
Yes, we sorted it out in the end, but we just have to be careful with such changes as it's unpleasant for devs to have to fight against problems which come out of nowhere and are out of their hands :)

**Comment by nickvergessen** [comment]
Well usually I see such things on my own apps first, so there is always an example how to fix it. ;) I try my best to keep that up and not let it happen again.

**Comment by MorrisJobke** [comment]
> Yes, we sorted it out in the end, but we just have to be careful with such changes as it's unpleasant for app devs to have to fight against problems which come out of nowhere and are out of their hands :)

Out of nowhere? That are private namespace classes - we have everywhere big warnings not to use them. 😉

**Comment by nickvergessen** [comment]
Well Test\TestCase is an Exception

**Pull request merged**
