### PR TITLE
[stable12] Fix "Sign in as user" acceptance test

### PR DESCRIPTION
**Pull request by MorrisJobke**
Backport of #377 and #379 (ref #384)

### CODE REVIEW

**Comment by MorrisJobke** [comment]
```
Unable to create new service: GeckoDriverService
Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:07:36.161Z'
System info: host: 'travis-job-nextcloud-gallery-334710089', ip: '172.17.0.10', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.12-041412-generic', java.version: '1.8.0_151'
Driver info: driver.version: unknown
```

@danxuliu Any idea what this is about?

**Comment by danxuliu** [comment]
@MorrisJobke It could be related to #330 but I have not checked it thoroughly yet (and that is the reason why I had backported this PR only to _stable13_ ;-) ).

**Comment by MorrisJobke** [comment]
Rebased to contain #388

**Comment by MorrisJobke** [comment]
Worked 👍

**Pull request merged**
