### PR TITLE
Clean all superposed white backgrounds

### PR DESCRIPTION
**Pull request by skjnldsv**
See https://github.com/nextcloud/server/pull/1657

### CODE REVIEW

**Comment by oparoz** [comment]
Thank you for that. Ping me when it's merged in core. And btw, all commits now need to be signed-off before they can be merged.

**Comment by skjnldsv** [comment]
Ah snap! I forgot! Thanks!

**Comment by skjnldsv** [comment]
We can merge this one. Still a simple cleanup.
The server one will follow after the scss pr and some scss cleanup.
Right now we still don't need a white background here. :)

@oparoz

**Comment by oparoz** [comment]
Thanks for the note.
I (or someone else) need to test this with the background switcher to make sure it still works when we need to select a white background. Once confirmed, I'll merge it.

**Comment by oparoz** [comment]
I don't think it's going to fix anything as the white background is added via JS afterwards, but there is no harm in removing it.

**Comment by skjnldsv** [comment]
^^

**Comment by skjnldsv** [comment]
@oparoz Can you explain to me why there is a white background added on image opening?
I don't fully get the point of https://github.com/nextcloud/gallery/blob/484b964c5cd19b7dacacadc5ee7015ec964ca209/js/galleryview.js#L497

And more importantly, the `Gallery.config.albumDesign` is only set to null once in the js file, so I'm not sure this whole function is required. :) Can you check?

It's the only thing lft here that block the dark thee integration ;)

**Comment by oparoz** [comment]
The background is set via the gallery.cnf config files.
https://github.com/nextcloud/gallery/wiki/Gallery-configuration#album-configuration

White is the standard background colour. It could come from the Nextcloud theme is there is JS API for it.

**Pull request merged**
