### PR TITLE
Removed old code already present thanks to the files app

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix nextcloud/server#5337

### CODE REVIEW

**Comment by MariusBluem** [comment]
Thank you @skjnldsv 😍🙈
Since this is breaking the layout of Files-app, I would vote for backporting this to `stable13`

**Comment by skjnldsv** [comment]
I agree! :)

**Comment by MorrisJobke** [comment]
Please backport to stable13

**Comment by skjnldsv** [comment]
Damnit I forgot again!

**Comment by skjnldsv** [comment]
Backport in https://github.com/nextcloud/gallery/pull/406

**Pull request merged**
