### PR TITLE
Add confirmation button to share input

### PR DESCRIPTION
**Pull request by jancborchardt**
The Gallery app equivalent of https://github.com/nextcloud/server/pull/7196 cc @nickvergessen @oparoz @MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Moved to 14 (same as the server PR)

**Comment by danxuliu** [comment]
Ready for review!

I have adapted the commits from nextcloud/server#7196 to the gallery code (although there are no unit tests in this case, sorry ;-) ). Note, however, that things like avatars or not showing sharees already shared with in the dropdown (which are implemented in the server, but not in the gallery) were not included; only the changes related to the confirmation button were taken into account.

[Copy-pasting myself](https://github.com/nextcloud/server/pull/7196#issuecomment-374686930):
Now a share is added when clicking on the confirm button of the input field (or when pressing `Enter` on the input field). However, that only happens if the server returns a single exact match for that sharee; if no exact match is found for the input field value, or if there are more than one, no share is added and the autocomplete dropdown is shown again with the suggestions. I think that behaviour is less error prone for the user than simply adding a share with the first match found (and if the user wants to do that she just needs to wait until the autocomplete dropdown is shown and either click on the first item or simply press `Enter` (as the first item is focused automatically when the dropdown is shown)).

In this pull request the order of suggestions in the autocomplete dropdown has been slightly modified. Until now the order was _exact users, partial users, exact groups, partial groups, exact..._; now that order became _exact users, exact groups, exact..., partial users, partial groups, partial..._, which in my opinion is better as all the exact matches are now shown at the beginning.

Besides that certain behaviours were also improved (like no longer failing silently when getting the suggestions succeeded but failure content was returned (for example, if `OCSBadRequestException` was thrown [in the controller](https://github.com/nextcloud/server/blob/0a56d2185e79caf81f5160cb8503955d9c3108a6/apps/files_sharing/lib/Controller/ShareesAPIController.php#L120)), or keep showing the working icon while there are pending operations) and some minor details in the code (using `OC.Notification.showTemporary` instead of `OC.Notification.show` plus `OC.Notification.hide` after a timeout).

@nextcloud/designers

**Comment by MorrisJobke** [comment]
> Please wait until #421 is merged to merge this one (it will need a rebase).

Please rebase as #421 was merged.

**Comment by danxuliu** [comment]
>  Please rebase as #421 was merged.

Done!

**Comment by danxuliu** [comment]
As the equivalent pull request in server has not been backported this one should not be backported either to keep a consistent behaviour in Nextcloud 13; due to that I have removed the `backport-request` label.

**Pull request merged**
